name: Node.JS CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node.JS Environment
      uses: actions/setup-node@v2
        with:
          node-version: 16
    - name: Install Dependencies using NPM
      run: npm install --omit=optional --legacy-peer-deps
    - name: Run NPM test
      run: npm test
      env:
        CI: true
        
