on: 
  push:
    branches:
      - develop

name: Site Deployment
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.JS Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache NPM Packages
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
      - name: Setup, Build and Install Dependencies using Node.JS
        run: npm install && npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            
