on: 
  push:
    branches:
      - develop

name: Site Deployment
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.JS Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache NPM Packages
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies using NPM
        run: npm install --no-optional
      - name: Install scratch-blocks (a hack to fix the build for now)
        run: npm install scratch-blocks
      - name: Run the build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            
